PruebaNaitus/ViewComponents/IndicadoresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Prueba_Naitus.Models;
using System.Net;

namespace PruebaNaitus.ViewComponents
{
    public class IndicadoresViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            Indicador objSerie;
            List<Indicador> lista = new List<Indicador>();
            string[] codigos = {"uf","dolar","euro","utm" };
            for (int i=0;i<4;i++)
            {
               
                string url = "http://www.mindicador.cl/api/" + codigos[i] +"/"+ DateTime.Now.ToString("dd-MM-yyyy");
                string res = "";

                try
                {
                    WebClient web = new WebClient();
                    Stream stream = web.OpenRead(url);
                    using (StreamReader reader = new StreamReader(stream))
                    {
                        res = reader.ReadToEnd();
                    }

                    objSerie = JsonConvert.DeserializeObject<Indicador>(res);
                    lista.Add(objSerie);

                }
                catch (Exception ex)
                {
                    throw;
                }
            }

           

            return View(lista);
        }
    }
}

PruebaNaitus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebaNaitus</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PruebaNaitus.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PruebaNaitus</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CrearUsuario">Crear Usuario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Listar">Mostrar Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="UploadFile">Subir Imagen</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <nav>
        @await Component.InvokeAsync("Indicadores")
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PruebaNaitus - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
   
</body>
</html>